DjangoProjects/test1/page/urls.py
from django.conf.urls import url


from . import views

app_name = 'page_app'
urlpatterns = [
    url(r'^articles/?$', views.AllArticleView.as_view(), name='articles'),
    url(r'^articles/(?P<id_art>\d+)?/?(?P<page_num>\d+)?/?$', views.ArticleView.as_view(template_name = 'page/article.html'), name='article'),

    url(r'^reporters/$', views.AllReporterView.as_view(), name='reporters'),
    url(r'^reporters/(?P<id_rep>.*)/$', views.ReporterView.as_view(), name='reporter'),

    url(r'^persons/?$', views.AllPersonView.as_view(template_name = 'page/all_persons.html'), name='persones'),
    url(r'^persons/(?P<id_pers>\d+)?/?(?P<page>\d+)?/?$', views.PersonView.as_view(template_name = 'page/person.html'), name='persone'),
    # неименованная группа. Соответствует закомментированной строке в TestView self.test_list.append(self.args[0])
    #args и kwargs нельзя реализовывать в одной url. Для запуска неименованной группы надо ее раскоментировать и
    # закомментировать расположенную ниже
    #url(r'^testing/(\d+)/$', views.TestView.as_view(), name='testing'),
    url(r'^testing/(?P<test>\d+)/$', views.TestView.as_view(), name='testing'),
    url(r'^cbv/$',  views.CbvView.as_view(template_name = 'page/cbv.html'), name='cbv'),

    url((r'^add/reporters/$'), views.RepCreate.as_view(), name='reporter_add'),
    url((r'^update/reporters/(?P<id_rep>.*)/$'), views.RepUpdate.as_view(), name='reporter_update'),
    url((r'^delete/reporters/(?P<id_rep>.*)/$'), views.RepDelete.as_view(), name='reporter_delete'),

    url((r'^add/articles/$'), views.ArtCreate.as_view(), name='article_add'),
    url((r'^update/articles/(?P<id_art>\d+)/$'), views.ArtUpdate.as_view(), name='article_update'),
    url((r'^delete/articles/(?P<id_art>\d+)/$'), views.ArtDelete.as_view(), name='article_delete'),

    url((r'^add/persones/$'), views.PersCreate.as_view(), name='person_add'),
    url((r'^update/persones/(?P<id_pers>\d+)/$'), views.PersUpdate.as_view(), name='person_update'),
    url((r'^delete/persones/(?P<id_pers>\d+)/$'), views.PersDelete.as_view(), name='person_delete'),

    url(r'^.*$', views.index, name='index')
    ]

DjangoProjects/test1/test1/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from page import views


urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^admin/', admin.site.urls),
    url(r'^page/', include('page.urls'))
]

DjangoProjects/test1/page/templates/page/add.html
{% extends "base.html" %}
{% block title %}Adding :: new {{model_name}} {% endblock %}
{% block main %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add">
</form>

{% endblock %}

DjangoProjects/test1/page/templates/page/all_articles.html
{% extends "base.html" %}
{% block title %}All articles{% endblock %}
{% block main %}
    <ul>
    <h3>Articles:</h3>

    {% for item in latest %}
           <li><b><a href = '/page/articles/{{ item.id }}/'>{{ item.headline }} </a></b><i>{{ item.pub_date }}</i></li>
    {% endfor %}
     </ul>
 {% endblock %}

DjangoProjects/test1/page/templates/page/all_persons.html
{% extends "base.html" %}
{% block title %}All persons{% endblock %}
{% block main %}
    <ul>
    <h3>All persons:</h3>

    {% for item in out_list %}
           <li><b><a href = '/page/persons/{{ item.id }}/'>{{ item.name }} </a></b></li>
    {% endfor %}
 {% endblock %}

DjangoProjects/test1/page/templates/page/all_reporters.html
{% extends "base.html" %}
{% block title %}All reporters{% endblock %}
{% block main %}
    <ul>
    <h3>All reporters, who started to work at <i>{{year|date:'Y'}}</i></h3>

    {% for item in object_list %}
           <li><b><a href = "{% url 'page_app:reporter' item.id %}">{{ item.full_name }} </a></b>
           started to work {{item.work_begin|date:'j.E.Y'}}


           </li>
    {% endfor %}
{% endblock %}

DjangoProjects/test1/page/templates/page/article.html
{% extends "base.html" %}
{% block title %}{{art.headline}}{% endblock %}
{% block main %}
           <ul>
           <h3>Article:&nbsp;{{ art.headline }}</h3>
           <i></i>Published&nbsp;{{ art.pub_date }}&nbsp;</i>
           <b>Written by:<a href = "{% url 'page_app:reporter' art.reporter.id %}">{{ art.reporter }}</a></b>
           <p><i>{{art.content}}</i>
           <h3>Persons mentioned in the article {{ art.headline }}:</h3>
     {% if not pers_list %}
               <b>No persons mentioned</b>
     {%endif%}

     {% for item in pers_list %}

        {% include "page/person_up.html"  %}<p>

           </ul>
     {% endfor %}

 <a href = "{% url 'page_app:article' %}" ><h4>All articles</h4></a>

 <ul> <a href = "{% url 'page_app:article_update' art.id %}"><i>Update</i></a></ul>
 <ul> <a href = "{% url 'page_app:article_delete' art.id %}"><i>Delete</i></a></ul>

     <div id="page_number">
          {% if pers_list.has_previous %}
             <b><a href = "{% url 'page_app:article' art.id  %}/{{pers_list.previous_page_number}}/">&lt;&nbsp;{{pers_list.previous_page_number}}</a></b>
          {% endif %}
          {% if pers_list.paginator.num_pages > 1 %}
             &nbsp;&nbsp;&nbsp;{{pers_list.number}}&nbsp;&nbsp;&nbsp;
          {% endif %}
          {% if pers_list.has_next %}
             <b><a href = "{% url 'page_app:article' art.id  %}/{{pers_list.next_page_number}}/">{{pers_list.next_page_number}}&nbsp;&gt;</a></b>
          {% endif %}
     </div>

{% endblock %}

DjangoProjects/test1/page/templates/page/cbv.html
<h2>CBV test</h2>

{% for item in the_list %}
         <li><b>{{ item}}</b></li>
{% endfor %}
<p>
<p>
{% for item in all_list %}
     {% for elem in item %}
         <li><b>{{ elem }}</b></li>
     {% endfor %}
<p>
<p>
{% endfor %}

DjangoProjects/test1/page/templates/page/delete.html
{% extends "base.html" %}


{% block title %}Delete :: {{model_name}} ::

{{object.full_name}}{{object.headline}}{{object.name}}

{% endblock %}
{% block main %}
<h3>Caution!</h3>
<p></p>You are going to delete
<p><b><font color = 'red'>{{model_name}}&nbsp;"{{object.full_name}}{{object.headline}}{{object.name}}"</font></b>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Delete">
</form>

{% endblock %}

DjangoProjects/test1/page/templates/page/index.html
{% extends "base.html" %}
{% block title %}All we have{% endblock %}
{% block main %}
<h2> All we have</h2>
{% endblock %}

DjangoProjects/test1/page/templates/page/person.html
{% extends "base.html" %}
{% block title %}{{item.name}}{% endblock %}
{% block main %}
   {% include "page/person_up.html"  %}
   {% include "page/person_down.html" %}
{% endblock %}

DjangoProjects/test1/page/templates/page/person_down.html
    <h4>Mentioned in the articles:</h4>
    {%if not page_obj%}
    <b><font color = red>no article about this person</font></b>
    {%endif%}
    {% for subj in page_obj %}
       <li><i> Article name:&nbsp;</i><a href = "{% url 'page_app:article' subj.id %}/">{{ subj }}</a><i>, published {{subj.pub_date}}</i></li>
       <li><i>By reporter:&nbsp;</i><a href = '/page/reporters/{{ subj.reporter.id }}/'>{{ subj.reporter.full_name }}</a>&nbsp;</li>
       <p>
    {% endfor %}

    <div id="page_number">
          {% if page_obj.has_previous %}
             <b><a href = "{% url 'page_app:persone' item.id  %}/{{page_obj.previous_page_number}}">&nbsp;&lt;{{page_obj.previous_page_number}}</a></b>
          {% endif %}
          {% if page_obj.paginator.num_pages > 1 %}
             &nbsp;&nbsp;&nbsp;{{page_obj.number}}&nbsp;&nbsp;&nbsp;
          {% endif %}
          {% if page_obj.has_next %}
             <b><a href = "{% url 'page_app:persone' item.id  %}/{{page_obj.next_page_number}}">{{page_obj.next_page_number}}&nbsp;&gt;</a></b>
          {% endif %}
     </div>

       <a href = "{% url 'page_app:persones' %}"><h4>All persons</h4><a>
            <p><a href = "{% url 'page_app:person_update' item.id %}"><i>Update</i></a>
            <p> <a href = "{% url 'page_app:person_delete' item.id %}"><i>Delete</i></a>

DjangoProjects/test1/page/templates/page/rep_update.html
{% extends "base.html" %}
{% block title %}Update :: Reporter {{object.full_name}}{% endblock %}
{% block main %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

{% endblock %}

DjangoProjects/test1/page/templates/page/reporter.html
{% extends "base.html" %}
{% block title %}{{out_list.0.full_name}}{% endblock %}
{% block main %}
    <ul><h3>Reporter:</h3>
    <li><h3><b>{{ reporter.full_name }}</b></h3>
    <li>height: {{ reporter.height }}
    <li>weight: {{ reporter.weight }}
    <li>wage: {{ reporter.wage }}
    </ul>
    {% for item in out_list %}

        {% if forloop.first %}
            <ul><h3>Articles:</h3>
        {% endif %}


                       <li>Article headline: <a href = "/page/articles/{{ item.id }}/"><i>{{item.headline}}</i></a><br>
                       <li>Article publication date: <i>{{item.pub_date}}</i><p>


        {% if forloop.last %}
           </ul>
        {% endif %}

    {% endfor %}

  <ul><a href = '/page/reporters/'><h4>All reporters</h4></a></ul>
 <ul> <a href = "{% url 'page_app:reporter_update' reporter.id %}"><i>Update</i></a></ul>
 <ul> <a href = "{% url 'page_app:reporter_delete' reporter.id %}"><i>Delete</i></a></ul>
{% endblock %}

DjangoProjects/test1/page/templates/page/test.html
{% extends "base.html" %}
{% block title %}All we have{% endblock %}
{% block main %}

{{ test_list }}<p>



   <b><a href = "{% url 'page_app:testing' test_list.2  %}?id={{test_list.0}}&page_num={{test_list.1}}">look at link</a></b>

{% endblock %}

DjangoProjects/test1/page/templates/page/update.html
{% extends "base.html" %}
{% block title %}Update :: {{model_name}} :: 

{{object.full_name}}{{object.headline}}{{object.name}}

{% endblock %}
{% block main %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

{% endblock %}